// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BashSessionCreateRequest {
    /** Session ID. Auto-generated if not provided. */
    session_id?: string;
    /** Working directory for the new session (absolute path) */
    exec_dir?: string;
    /** Path to a shell snapshot script to source on session init */
    snapshot_path?: string;
}
