// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         command: "command"
 *     }
 */
export interface BashExecRequest {
    /** Target session ID. If not provided, a new session is created automatically. */
    session_id?: string;
    /** Shell command to execute */
    command: string;
    /** Working directory for command execution (absolute path) */
    exec_dir?: string;
    /** Extra environment variables to inject for this command only. */
    env?: Record<string, string | undefined>;
    /** If true, return immediately with running status. Use /output to poll results. */
    async_mode?: boolean;
    /** HTTP timeout (seconds). Only effective when async_mode=false. If the command does not complete within this time, HTTP returns running status and the command continues in the background. Use /output to get results. */
    timeout?: number;
    /** Hard execution timeout (seconds). When reached, the process is killed and status becomes timed_out. None means no limit. */
    hard_timeout?: number;
    /** Maximum character length for stdout/stderr in the response. When output exceeds this limit, middle truncation is applied (head and tail preserved, middle replaced with a marker). Only effective in sync mode (async_mode=false). Set to 0 to disable truncation. */
    max_output_length?: number;
}
