// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Serializable command status info (for API responses).
 */
export interface BashCommandInfo {
    /** Unique command identifier */
    command_id: string;
    /** The command string */
    command: string;
    /** Command execution status */
    status: Sandbox.CommandStatus;
    /** Exit code (when completed) */
    exit_code?: number;
}
