// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface RestartRequest {
    mode?: Sandbox.Mode;
    url_blocklist?: string[];
    url_allowlist?: string[];
    locale?: string;
}
