// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "path",
 *         pattern: "pattern"
 *     }
 */
export interface FileGrepRequest {
    /** Directory path to search */
    path: string;
    /** Search pattern (regex or fixed string) */
    pattern: string;
    /** File glob filters to include (e.g., ["*.py", "*.ts"]) */
    include?: string[];
    /** Glob patterns to exclude (e.g., ["node_modules", "*.min.js"]) */
    exclude?: string[];
    /** Case insensitive search */
    case_insensitive?: boolean;
    /** Treat pattern as literal string, not regex */
    fixed_strings?: boolean;
    /** Number of lines before each match (-B) */
    context_before?: number;
    /** Number of lines after each match (-A) */
    context_after?: number;
    /** Maximum number of matches to return */
    max_results?: number;
    /** Skip files larger than this size (e.g., 1M, 500K) */
    max_file_size?: string;
    /** Search recursively */
    recursive?: boolean;
}
